# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7773f8969e745a8e4c82162b54c8bb501256d31e00b11770d62302dbc89f9b03c359c1ea23fb872088206225d232392b601806a17ba245e19fde3f15f0192107

test:
  secret_key_base: 5a5a08fbec1349f2073910a1f4870e3038c98fb931b554cfc7785b2cb235a713fbc22d3b7e106acf636d3a1f8d6c2d3a9ec4d88471180746beaa0854ce475e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
